import 'package:cloud_firestore/cloud_firestore.dart';

Future<void> uploadUsers() async {
  final firestore = FirebaseFirestore.instance;

  final users = [
    {
      "uid": "sCq32l55K6dgG3i3dip6cy3tsMb2",
      "employeeCode": 1,
      "name": "Venkatesh",
      "email": "venkatesh@qdesk.com",
      "department": "Admin",
      "role": "admin",
      "reportsTo": "",
    },
    {
      "uid": "c4MF99OEhrgTuFGvOhJbdYrL3rB3",
      "employeeCode": 2,
      "name": "Kiran Sakthi Shanmugam",
      "email": "kiran@qdesk.com",
      "department": "Admin",
      "role": "admin",
      "reportsTo": "",
    },
    {
      "uid": "6KRLNd9Er0dYyS8z1atRSmY3Lkg2",
      "employeeCode": 3,
      "name": "Dinesh Kumar G",
      "email": "dinesh@qdesk.com",
      "department": "Development",
      "role": "manager",
      "reportsTo": "Kiran Sakthi Shanmugam",
    },
    {
      "uid": "5PGCZOuRDIZhBT0SsvySIEdRqmq2",
      "employeeCode": 4,
      "name": "Pravin Kumar",
      "email": "pravin@qdesk.com",
      "department": "Training",
      "role": "manager",
      "reportsTo": "Kiran Sakthi Shanmugam",
    },
    {
      "uid": "IM9PLdhSn9UliB5CBWMn5hCXgv32",
      "employeeCode": 5,
      "name": "Krushnaraj",
      "email": "krushna@qdesk.com",
      "department": "Training",
      "role": "manager",
      "reportsTo": "Kiran Sakthi Shanmugam",
    },
    {
      "uid": "a9aGf1giKOcobm1lsw8XxoQq4iu1",
      "employeeCode": 6,
      "name": "Manu Thambi",
      "email": "manu@qdesk.com",
      "department": "Training",
      "role": "manager",
      "reportsTo": "Kiran Sakthi Shanmugam",
    },
    {
      "uid": "96lywv7JihRGHySmuZsjyiAvuhK2",
      "employeeCode": 7,
      "name": "Mukilan Selvaraj",
      "email": "mukilan@qdesk.com",
      "department": "Training",
      "role": "employee",
      "reportsTo": "Pravin Kumar",
    },
    {
      "uid": "Rbn57mePuMTZuYBe8EVDqnfdn023",
      "employeeCode": 8,
      "name": "Mathiyarasan",
      "email": "mathiyarasan@qdesk.com",
      "department": "Training",
      "role": "employee",
      "reportsTo": "Pravin Kumar",
    },
    {
      "uid": "zq5V8XW3D6N1b20o0jD7ZvYLOrl3",
      "employeeCode": 9,
      "name": "Pavithra Kannan",
      "email": "pavithra@qdesk.com",
      "department": "Training",
      "role": "employee",
      "reportsTo": "Pravin Kumar",
    },
    {
      "uid": "nbcahEoIlIY0x8TxInjuFtGmcCs2",
      "employeeCode": 10,
      "name": "Maheshwaran",
      "email": "maheshwaran@qdesk.com",
      "department": "Training",
      "role": "employee",
      "reportsTo": "Pravin Kumar",
    },
    {
      "uid": "OGyEe23GxGTOySs9JJCCVAhAXHw1",
      "employeeCode": 11,
      "name": "Nithruja",
      "email": "nithruja@qdesk.com",
      "department": "Training",
      "role": "employee",
      "reportsTo": "Pravin Kumar",
    },
    {
      "uid": "UNKeKjxRhEWU7oymoiHn1Ud6id12",
      "employeeCode": 12,
      "name": "Vasanth",
      "email": "vasanth@qdesk.com",
      "department": "Training",
      "role": "employee",
      "reportsTo": "Pravin Kumar",
    },
    {
      "uid": "t7adM0CPrwcFqOimH5Yx2buxWUy2",
      "employeeCode": 14,
      "name": "Jothi Prasad",
      "email": "jothi@qdesk.com",
      "department": "Training",
      "role": "employee",
      "reportsTo": "Pravin Kumar",
    },
    {
      "uid": "zBVCFDWLhkNfoBqhFbfPbANG7i62",
      "employeeCode": 15,
      "name": "Shaik Immamudin",
      "email": "shaik@qdesk.com",
      "department": "Training",
      "role": "employee",
      "reportsTo": "Pravin Kumar",
    },
    {
      "uid": "It8wDUsohuQG3LFOzCOz3t8xXGD3",
      "employeeCode": 16,
      "name": "Esakki Raghul",
      "email": "esakki@qdesk.com",
      "department": "Training",
      "role": "employee",
      "reportsTo": "Pravin Kumar",
    },
    {
      "uid": "ASefRvwsRcc57aZBbTGwCPxm4hM2",
      "employeeCode": 17,
      "name": "Prathip Kumar",
      "email": "prathip@qdesk.com",
      "department": "Operations",
      "role": "employee",
      "reportsTo": "Kiran Sakthi Shanmugam",
    },
    {
      "uid": "W0rrOOB7wOSJ25akw3WKqOlaD4s1",
      "employeeCode": 18,
      "name": "Dheeksha",
      "email": "dheeksha@qdesk.com",
      "department": "Training",
      "role": "employee",
      "reportsTo": "Pravin Kumar",
    },
    {
      "uid": "g9rs7AAdjjVCJ6BXbSd9iNkFgPH2",
      "employeeCode": 19,
      "name": "Gokul",
      "email": "gokul@qdesk.com",
      "department": "Training",
      "role": "employee",
      "reportsTo": "Pravin Kumar",
    },
    {
      "uid": "zptigpoMmxaMeAjBJiogNrWn3Ns1",
      "employeeCode": 23,
      "name": "Vaishiya",
      "email": "vaishiya@qdesk.com",
      "department": "Training",
      "role": "employee",
      "reportsTo": "Pravin Kumar",
    },
    {
      "uid": "EqbTgO44a8Oly29XkctH1OzxKib2",
      "employeeCode": 24,
      "name": "Jindo",
      "email": "jindo@qdesk.com",
      "department": "Training",
      "role": "employee",
      "reportsTo": "Pravin Kumar",
    },
  ];

  for (var user in users) {
    final uid = user["uid"] as String;

    await firestore.collection('users').doc(uid).set({
      ...user,
      "isActive": true,
      "createdAt": Timestamp.now(),
    });
  }

  print("All users uploaded successfully");
}